# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Pipfile.lock" }}-{{ checksum "Makefile" }}

      - run:
          name: install dependencies
          command: |
            make download_tagger

      - save_cache:
          paths:
            - ./tagger
          key: v1-dependencies-{{ checksum "Pipfile.lock" }}-{{ checksum "Makefile" }}

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
