# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.4
        environment:
          PIPENV_VENV_IN_PROJECT: true

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Pipfile.lock" }}-{{ checksum "make.sh" }}

      - run:
          name: Execute
          command: |
            pipenv install
            ./make.sh setup
            ./make.sh execute

      - store_artifacts:
          path: models/features_pipeline.joblib

      - save_cache:
          paths:
            - ".venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.6/site-packages"
            - "./tagger"
          key: v1-dependencies-{{ checksum "Pipfile.lock" }}-{{ checksum "make.sh" }}

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
